version: '3.1'
services:
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    env_file: ../../../../../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}    

  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080